{{- if and .Values.application.enabled .Values.autoscale.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "deploy.fullName" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "deploy.fullName" . }}
  minReplicas: {{ .Values.autoscale.min }}
  maxReplicas: {{ .Values.autoscale.max }}
  metrics:
    {{- if .Values.autoscale.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscale.cpu.target }}
    {{- end }}
    {{- if .Values.autoscale.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscale.memory.target }}
    {{- end }}
    {{- with .Values.autoscale.metrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.autoscale.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}