name: 发布

on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: 取码
        uses: actions/checkout@v4

      - name: 配置仓库
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: 配置工具
        uses: azure/setup-helm@v4

      - name: 编译
        run: |
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm dependency build "$chart"
            fi
          done

      - name: 上传
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: ./charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"